# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pXpdBe4yreJ7m8DHIDE-vLw9EnWmJJOu
"""

!pip install mysql-connector-python

import mysql.connector

connection = mysql.connector.connect(
  host = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com",
  port = 4000,
  user = "bBdMPga4tbKX2G8.root",
  password = "7BDg7rhupeZAdIok",
  database = "PROJECT",
)
mycursor=connection.cursor()

!pip install tabulate

mycursor.execute("SELECT * FROM PROJECT.orderlast  ")
out=mycursor.fetchall()
from tabulate import tabulate
print(tabulate(out,headers=[i[0] for i in mycursor.description],  tablefmt='psql'))

mycursor.execute("""SELECT  e.order_id,od.sub_category, SUM(od.quantity * od.discount_price) AS total_revenue
FROM orderlast od
JOIN orderfirst e ON od.order_id = e.order_id
GROUP BY e.order_id, od.sub_category
ORDER BY total_revenue DESC
LIMIT 10;""")
out=mycursor.fetchall()
from tabulate import tabulate
print(tabulate(out,headers=[i[0] for i in mycursor.description],  tablefmt='psql'))

mycursor.execute("""SELECT  e.order_id,e.sub_category, SUM(e.quantity * e.discount_price) AS HIGH_revenue
FROM orderlast e
GROUP BY e.order_id, e.sub_category
ORDER BY HIGH_revenue DESC
LIMIT 10;""")
out=mycursor.fetchall()
from tabulate import tabulate
print(tabulate(out,headers=[i[0] for i in mycursor.description],  tablefmt='psql'))

mycursor.execute("""SELECT orderfirst.city,SUM(orderlast.profit) AS total_profit
FROM orderfirst
JOIN orderlast ON orderfirst.order_id = `orderlast`.`order_id`
GROUP BY orderfirst.city
ORDER BY total_profit DESC
LIMIT 5;""")
out=mycursor.fetchall()
from tabulate import tabulate
print(tabulate(out,headers=[i[0] for i in mycursor.description],  tablefmt='psql'))

mycursor.execute("""SELECT category,SUM(discount_price) AS total_discount
FROM PROJECT.orderlast
GROUP BY category;""")
out=mycursor.fetchall()
from tabulate import tabulate
print(tabulate(out,headers=[i[0] for i in mycursor.description],  tablefmt='psql'))

mycursor.execute("""SELECT category,AVG(sale_price) AS average_sale_price
FROM orderlast
GROUP BY category;""")
out=mycursor.fetchall()
from tabulate import tabulate
print(tabulate(out,headers=[i[0] for i in mycursor.description],  tablefmt='psql'))

mycursor.execute("""SELECT f.region, AVG(l.sale_price) AS averagesale_price
FROM orderfirst f
JOIN orderlast AS l ON f.order_id = l.order_id
GROUP BY f.region
ORDER BY AVG(l.sale_price) DESC;""")
out=mycursor.fetchall()
from tabulate import tabulate
print(tabulate(out,headers=[i[0] for i in mycursor.description],  tablefmt='psql'))

mycursor.execute("""SELECT category,SUM(profit) AS total_profit
FROM orderlast
GROUP BY category;""")
out=mycursor.fetchall()
from tabulate import tabulate
print(tabulate(out,headers=[i[0] for i in mycursor.description],  tablefmt='psql'))

mycursor.execute("""SELECT f.segment, SUM(l.quantity) AS total_quantity
FROM orderfirst f
JOIN orderlast l ON f.order_id = l.order_id
GROUP BY f.segment
ORDER BY total_quantity DESC
;""")
out=mycursor.fetchall()
from tabulate import tabulate
print(tabulate(out,headers=[i[0] for i in mycursor.description],  tablefmt='psql'))

mycursor.execute("""SELECT f.region,AVG(l.discount_percent) AS average_discount_percentage
FROM orderfirst f
JOIN orderlast l ON f.order_id = l.order_id
GROUP BY f.region;""")
out=mycursor.fetchall()
from tabulate import tabulate
print(tabulate(out,headers=[i[0] for i in mycursor.description],  tablefmt='psql'))

mycursor.execute("""SELECT category,SUM(profit) AS total_profit
FROM orderlast
GROUP BY category
ORDER BY total_profit DESC limit 1;""")
out=mycursor.fetchall()
from tabulate import tabulate
print(tabulate(out,headers=[i[0] for i in mycursor.description],  tablefmt='psql'))

mycursor.execute("""SELECT YEAR(orderfirst.order_date) AS year,SUM(orderlast.sale_price) AS total_revenue
FROM orderfirst
JOIN orderlast ON orderfirst.order_id = orderlast.order_id
GROUP BY YEAR(orderfirst.order_date);""")
out=mycursor.fetchall()
from tabulate import tabulate
print(tabulate(out,headers=[i[0] for i in mycursor.description],  tablefmt='psql'))